Q1 Basic NumPy Array 

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [ ]:
# (a)
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print()
rev1 = arr[::-1]
rev2 = np.flip(arr)
print(rev1)
print(rev2)


[5 4 6 3 2 1]
[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods

In [ ]:
# (b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
f1 = array1.flatten()
f2 = array1.ravel()
print(f1)
print(f2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
# (c)
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

True


(d) Find the most frequent value and their indice(s) in the following arrays: 
i.  x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii.  y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [10]:
# (d)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])
def freq(arr):
    val = np.bincount(arr).argmax()
    print(f"element = {val}, indeces = {np.where(arr == val)}")

freq(x)
freq(y)

element = 1, indeces = (array([0, 5, 7, 8, 9]),)
element = 3, indeces = (array([ 4,  8,  9, 10]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
i.  Sum of all elements 
ii.  Sum of all elements row-wise  
iii.  Sum of all elements column-wise

In [50]:
# (e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"Sum = {np.sum(gfg)}")
print(f"Sum of Columns = {np.sum(gfg, axis=0)}")
print(f"Sum of Rows =\n {np.sum(gfg, axis=1)}")

Sum = 45
Sum of Columns = [[20  9 16]]
Sum of Rows =
 [[14]
 [16]
 [15]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
i.  Sum of diagonal elements 
ii.  Eigen values of matrix 
iii.  Eigen vectors of matrix 
iv.  Inverse of matrix 
v.  Determinant of matrix 

In [49]:
# (f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]) 
print(f"Sum of diagnol = {np.sum(np.diag(n_array))}") # (i)
print(f"Sum of diagnol = {np.trace(n_array)}") # (i)
print(f"Eigen values =\n {np.linalg.eig(n_array)[0]}")
print(f"Eigen vector =\n {np.linalg.eig(n_array)[1]}")
print(f"Inverse =\n {np.linalg.inv(n_array)}")
print(f"Determinant = {np.linalg.det(n_array)}")

Sum of diagnol = 176
Sum of diagnol = 176
Eigen values =
 [98.16835147 28.097044   49.73460452]
Eigen vector =
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse =
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant = 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy: 
i.  p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
ii.  p = [[1, 2], [2, 3], [4, 5]] 
q = [[4, 5, 1], [6, 7, 2]]

In [47]:
# (g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]] )

def calc(p, q):
    print(f"Multipication =\n {np.dot(p, q)}")
    if p.shape == q.shape:
        print(f"Covariance =\n {np.cov(p.flatten(), q.flatten())}")
    else:
        print("Shape mismatch")

calc(p1, q1)
calc(p2, q2)

Multipication =
 [[16 19]
 [26 31]]
Covariance =
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Multipication =
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Shape mismatch


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product?

In [2]:
# (h)
x = np.array([[2, 3, 4], [3, 2, 9]]) 
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f"Inner =\n {np.inner(x, y)}")
print(f"Outer =\n {np.outer(x.flatten(), y.flatten())}")
print(f"Cartessian =\n {np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)}")

Inner =
 [[17 52]
 [13 62]]
Outer =
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartessian =
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2 NumPy Mathematics and Statistics

(a)  For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
i.  Find element-wise absolute value 
ii.  Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row. 
iii.  Mean, Median and Standard Deviation of flattened array, of each column, and 
each row

In [ ]:
# (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])
print(f"Element-wise Absoulte = \n{np.abs(array)}")
f = array.flatten()
for i in [25, 50, 75] :
    print(f"{i}th Percentile = {np.percentile(f, i)}")
    print(f"{i}th Percentile Row = {np.percentile(array, i, axis=1)}")
    print(f"{i}th Percentile Column = {np.percentile(array, i, axis=0)}")

print(f"Mean = {np.mean(array.flatten())}")
print(f"Median = {np.median(array.flatten())}")
print(f"Standard Deviation = {np.std(array.flatten())}")
print("Row")
print(f"Mean = {np.mean(array, axis=1)}")
print(f"Median = {np.median(array, axis=1)}")
print(f"Standard Deviation = {np.std(array, axis=1)}")
print("Column")
print(f"Mean = {np.mean(array, axis=0)}")
print(f"Median = {np.median(array, axis=0)}")
print(f"Standard Deviation = {np.std(array, axis=0)}")

Element-wise Absoulte = 
[[1 2 3]
 [4 5 6]]
25th Percentile = -3.5
25th Percentile Row = [-0.5 -5. ]
25th Percentile Column = [-2.75 -0.25 -3.75]
50th Percentile = -0.5
50th Percentile Row = [ 1. -4.]
50th Percentile Column = [-1.5  1.5 -1.5]
75th Percentile = 2.5
75th Percentile Row = [2.  0.5]
75th Percentile Column = [-0.25  3.25  0.75]
Mean = -0.5
Median = -0.5
Standard Deviation = 3.8622100754188224
Row
Mean = [ 0.66666667 -1.66666667]
Median = [ 1. -4.]
Standard Deviation = [2.05480467 4.78423336]
Column
Mean = [-1.5  1.5 -1.5]
Median = [-1.5  1.5 -1.5]
Standard Deviation = [2.5 3.5 4.5]


(b)  For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values

In [11]:
# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(f"Floor = {np.floor(a)}")
print(f"Ceil = {np.ceil(a)}")
print(f"Truncated = {np.trunc(a)}")
print(f"Rounded = {np.round(a)}")

Floor = [-2. -2. -1.  0.  1.  1.  3.]
Ceil = [-1. -1. -0.  1.  2.  2.  3.]
Truncated = [-1. -1. -0.  0.  1.  1.  3.]
Rounded = [-2. -2. -0.  0.  2.  2.  3.]


Q3 Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i.  Sorted array 
ii.  Indices of sorted array 
iii.  4 smallest elements 
iv.  5 largest elements

In [ ]:
# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(f"Array = {(array)}")
print(f"Sorted = {np.sort(array)}")
print(f"Index = {np.argsort(array)}")
print(f"4 Smallest = {np.sort(array)[:4]}")
print(f"4 Smallest = {np.sort(array)[-5:]}")

Array = [ 10  52  62  16  16  54 453]
Sorted = [ 10  16  16  52  54  62 453]
Index = [0 3 4 1 5 2 6]
4 Smallest = [10 16 16 52]
4 Smallest = [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
i.  Integer elements only 
ii.  Float elements only

In [ ]:
# (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(f"Array = {(array)}")
print(f"Integers = {array[array == array.astype(int)]}")
print(f"Floats = {array[array != array.astype(int)]}")  # if i use astype float returns all as every element has decimal

Array = [1.  1.2 2.2 2.  3.  2. ]
Integers = [1. 2. 3. 2.]
Floats = [1.2 2.2]


Q4 Image

(a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images)

In [ ]:
# (a)


(b) Load the saved file into jupyter notebook?

In [ ]:
# (b)